# Generated by Django 3.0.1 on 2020-01-04 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191230_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloggingCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_category', models.CharField(max_length=200)),
                ('category_summary', models.CharField(max_length=200)),
                ('category_slug', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='blogging',
            name='blog_slug',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.CreateModel(
            name='BloggingSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_series', models.CharField(max_length=200)),
                ('series_summary', models.CharField(max_length=200)),
                ('blog_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.BloggingCategory', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.AddField(
            model_name='blogging',
            name='blog_series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.BloggingSeries', verbose_name='Series'),
        ),
    ]
