# Generated by Django 3.0.1 on 2020-01-04 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200104_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogging',
            name='blog_series',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.BloggingSeries', verbose_name='Series'),
        ),
    ]
